AWSTemplateFormatVersion: '2010-09-09'
Description: 'Initilizer cfn template for the 24hour-ssh project.'  
Parameters:
    InstanceTypeParameter:
        Type: String
        Default: t1.micro 
        Description: Parameter set as t1.micro by default. 
Resources:
    EC2Instance1:
        Type: AWS::EC2::Instance
        Properties:
            
    EC2Instance2:
        Type: AWS::EC2::Instance
        Properties:
        
    EC2Instance3:
        Type: AWS::EC2::Instance
        Properties: 