AWSTemplateFormatVersion: '2010-09-09'
Description: 'Should create a basic ec2 instance.'
Parameters: 
    InstanceTypeParameter:
        Type: String
        Default: t1.micro 
        Description: Parameter set as t1.micro. 
Resources:
    Ec2Instance:
        Type: AWS::EC2::Instance
        Properties:
            InstanceType:
                Ref: InstanceTypeParameter
            ImageId: ami-4e700e36